language: perl
matrix:
  include:
  - perl: "5.30"
  - perl: "5.28"
  - perl: "5.26"
  - perl: "5.24"
  - perl: "5.22"
  - perl: "5.20"
    dist: trusty
  - perl: "5.18"
    dist: trusty
  - perl: "5.16"
    dist: trusty
  - perl: "5.14"
    dist: trusty
  - perl: "5.12"
    dist: trusty
  - perl: "5.10"
    dist: trusty
env:
  - REDIS_VERSION=5.0.5
  - REDIS_VERSION=4.0.14
  - REDIS_VERSION=3.2.13
  - REDIS_VERSION=2.8.24
cache:
  directories:
  - redis-$REDIS_VERSION
  - extlib
install:
  - test -e redis-$REDIS_VERSION/src/redis-server || ( wget https://github.com/antirez/redis/archive/$REDIS_VERSION.tar.gz && tar xzf $REDIS_VERSION.tar.gz && make -C redis-$REDIS_VERSION )
  - cpanm -L extlib --quiet --installdeps --notest .
script:
  - export PATH=$PWD/redis-$REDIS_VERSION/src:$PATH
  - export PERL5LIB=$PWD/extlib/lib/perl5:$PERL5LIB
  - redis-server --version
  - perl Build.PL
  - prove -lv t
